version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: sql-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  mongodb:
    image: "mongo:latest"
    container_name: mongo-container
    ports:
      - "27017:27017"
    restart: "always"
    volumes:
      - "mongodb_data:/data/db"


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  sql_data:
    driver: local
  mongodb_data:
    driver: local
   
networks:
  default:
    external:
      name: mydockernetwork
